//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace As.Posterr.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("As.Posterr.Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty.
        /// </summary>
        internal static string CannotBeEmpty {
            get {
                return ResourceManager.GetString("CannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post is invalid.
        /// </summary>
        internal static string InvalidPost {
            get {
                return ResourceManager.GetString("InvalidPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user is not allowed to post more than {0} posts in one day.
        /// </summary>
        internal static string LimitPostsExceeded {
            get {
                return ResourceManager.GetString("LimitPostsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum of {0} characters is allowed for {1}.
        /// </summary>
        internal static string MaximunCharactersXcharactesIsAllowdForY {
            get {
                return ResourceManager.GetString("MaximunCharactersXcharactesIsAllowdForY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not follow this user.
        /// </summary>
        internal static string NotFollowingTheUser {
            get {
                return ResourceManager.GetString("NotFollowingTheUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric characters can be used for {0}.
        /// </summary>
        internal static string OnlyAphanumericCharactesIsAllowedForX {
            get {
                return ResourceManager.GetString("OnlyAphanumericCharactesIsAllowedForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already follow this user.
        /// </summary>
        internal static string UserAlreadyFollowing {
            get {
                return ResourceManager.GetString("UserAlreadyFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users cannot follow themselves.
        /// </summary>
        internal static string UserCannotFollowThemselves {
            get {
                return ResourceManager.GetString("UserCannotFollowThemselves", resourceCulture);
            }
        }
    }
}
